---

- name: Import dconf settings
  shell: dconf load / < "{{ item }}"
  with_fileglob:
    - "assets/gnome/*.dconf"

- name: Install Gnome extensions
  command:
    cmd: "{{ homedir }}/.dotfiles/bin/.local/bin/install-gnome-extension -x {{ item }}"
  with_items: "{{ gnome_extensions }}"