---
# tasks file for packages

- name: Install Homebrew taps
  homebrew_tap:
    name: "{{ taps }}"

- name: Install Homebrew packages
  homebrew:
    name: "{{ formulas }}"

- name: Install Homebrew casks
  homebrew_cask:
    name: "{{ casks }}"
    accept_external_apps: True

- name: Install Mac App Store applications
  command:
    cmd: "/usr/local/bin/mas install {{ item }}"
  with_items: "{{ apps }}"