---
# tasks file for dotfiles

- name: Create dotfile directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item.path }}"
    state: directory
    mode: '0755'
  with_filetree: dotfiles/
  when: item.state == 'directory'

- name: Apply dotfiles
  copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path }}"
    mode: '0755'
  with_filetree: dotfiles/
  when: item.state == 'file'

- name: Create vim extensions directory path
  file:
    path: "{{ vim_extensions_path }}"
    state: directory
    mode: '0755'

- name: Install vim-airline
  git:
    repo: https://github.com/vim-airline/vim-airline.git
    dest: "{{ vim_extensions_path }}/vim-airline"
    depth: '1'
    version: 'v0.11'
    update: False

- name: Install vim-airline-themes
  git:
    repo: https://github.com/vim-airline/vim-airline-themes.git
    dest: "{{ vim_extensions_path }}/vim-airline-themes"
    depth: '1'