---

- name: Set 'look and feel' to Breeze theme
  command:
    cmd: lookandfeeltool --apply org.kde.breeze.desktop

- name: Make double-click the default
  command:
    cmd: kwriteconfig5 --file kdeglobals --group "KDE" --key "SingleClick" "false"

- name: Make caps lock a control key
  command:
    cmd: kwriteconfig5 --file kxkbrc --group "Layout" --key "Options" "ctrl:nocaps"

- name: Copy desktop settings
  copy:
    src: assets/plasma-org.kde.plasma.desktop-appletsrc
    dest: "{{ homedir }}/.config/plasma-org.kde.plasma.desktop-appletsrc"

- name: Copy kate editor settings
  copy:
    src: assets/kde/katerc
    dest: "{{ homedir }}/.config/katerc"