---

- name: Load common variables
  include_vars: "os/{{ ansible_distribution }}"

- name: Call specific OS tasks
  include_tasks: "os/{{ ansible_distribution }}"

- name: Setup home environment
  include_tasks: dotfiles

- name: Setup development environment
  include_tasks: devenv

- name: Setup desktop environment
  include_tasks: "{{ desktop }}"