---

- name: Load desktop environment variables
  include_vars: "de/{{ desktop }}.yml"

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Install repos
  include_tasks: repos
  become: True

- name: Install OS packages
  become: True
  package:
    name: "{{ distro_packages }} + {{ de_packages }}"
    state: present