---

- name: Load desktop environment variables
  include_vars: "de/{{ desktop }}.yml"

- name: Install Homebrew taps
  homebrew_tap:
    name: "{{ taps }}"

- name: Install Homebrew packages
  homebrew:
    name: "{{ formulas }}"

- name: Install Homebrew casks
  homebrew_cask:
    name: "{{ casks }}"

- name: Install Mac App Store applications
  command:
    cmd: "/usr/local/bin/mas install {{ item }}"
  with_items: "{{ apps }}"