---
# tasks file for repositories

- name: Install "rpmfusion-free" repo
  yum:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Install "rpmfusion-nonfree" repo
  yum:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Install gpg keys
  rpm_key:
    key: "{{ item.gpgkey }}"
  loop: "{{ repos }}"

- name: Install repositories
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    includepkgs: "{{ item.includepkgs | default('') }}"
    gpgcheck: "{{ item.gpgcheck | default(True) }}"
    gpgkey: "{{ item.gpgkey }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | default(False) }}"
    skip_if_unavailable: "{{ item.skip_if_unavailable | default(True) }}"
  loop: "{{ repos }}"