#!/bin/bash

set -eu

pushd /usr/local/srv >/dev/null 2>&1
sudo git pull
popd >/dev/null 2>&1

sudo /opt/puppetlabs/bin/puppet apply /usr/local/srv/puppet/manifests/site.pp \
  --hiera_config /usr/local/srv/puppet/hiera.yaml \
  --modulepath /usr/local/srv/puppet/modules
