#!/bin/bash

set -eu

puppet_dir="/srv/puppet"

pushd "$puppet_dir" >/dev/null 2>&1
sudo git pull
popd >/dev/null 2>&1

sudo /opt/puppetlabs/bin/puppet apply $puppet_dir/manifests/site.pp \
  --hiera_config $puppet_dir/hiera.yaml \
  --modulepath $puppet_dir/modules
