---
- name: MacOS Workstation
  hosts: localhost
  vars:
    desktop: "{{ ansible_distribution }}"
    shell: /usr/local/bin/zsh
    vscode: '/usr/local/bin/code'
    vscode_config: "{{ homedir }}/Library/Application Support/VSCode"
  roles:
    - packages
    - dotfiles
    - environment
    - desktop