---
- name: Linux Workstation
  hosts: localhost
  vars:
    desktop: "{{ ansible_env.XDG_CURRENT_DESKTOP | lower }}"
    shell: /usr/bin/zsh
    vscode: '/usr/bin/code'
  roles:
    - repositories
    - packages
    - dotfiles
    - environment
    - desktop