---
- name: Linux Workstation
  hosts: localhost
  vars:
    desktop: "{{ ansible_env.XDG_CURRENT_DESKTOP | lower }}"
    vscodium: '/usr/bin/codium'
  roles:
    - repositories
    - packages
    - dotfiles
    - environment
    - desktop