---
- name: Linux Workstation
  hosts: localhost
  vars:
    desktop: "{{ ansible_env.XDG_CURRENT_DESKTOP | lower }}"
    vscodium: '/usr/bin/codium'
    gnome_extensions:
      - 1011 # dynamic-panel-transparency
  roles:
    - repositories
    - packages
    - dotfiles
    - environment
    - desktop